models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./models:/app
    ports:
      - "8001:8000"
    command: bash -c "python manage.py makemigrations youbet && python manage.py migrate && python manage.py loaddata db.json && mod_wsgi-express start-server --working-directory ./ --reload-on-changes ./models/wsgi.py"
    
exp:
    image: tp33/django
    links:
      - models:models-api
      - kafka:kafka
      - es:es
    volumes:
      - ./exp:/app
    ports:
      - "8002:8000"
    command: bash -c "mod_wsgi-express start-server --reload-on-changes --log-to-terminal ./exp/wsgi.py"
    
web:
  image: tp33/django
  links:
    - exp:exp-api
  volumes:
    - ./web:/app
  ports:
    - "8000:8000"
  command: bash -c "python manage.py migrate && mod_wsgi-express start-server --reload-on-changes --log-to-terminal ./web/wsgi.py"

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka
   
es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"

batch:
   image: tp33/django
   container_name: batch
   volumes:
    - .:/app
   links:
      - kafka:kafka
      - es:es
   command: bash -c "python batch-script.py"