# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-01 17:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youbet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joined_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
