# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-01 17:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youbet', '0002_user_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='initiation',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
