# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-05 01:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youbet', '0003_bet_initiation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='bet_id',
        ),
        migrations.RemoveField(
            model_name='response',
            name='user_id',
        ),
        migrations.AddField(
            model_name='bet',
            name='category',
            field=models.CharField(default='misc', max_length=50),
        ),
        migrations.AddField(
            model_name='bet',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='bet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youbet.Bet'),
        ),
        migrations.AddField(
            model_name='response',
            name='resp_timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='response',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youbet.User'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='initiation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
