# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-29 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youbet', '0003_auto_20171016_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reccomendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_items', models.CharField(max_length=300)),
                ('item_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='youbet.Bet')),
            ],
        ),
    ]
